### PR TITLE
Remove empty __init__.pyi files

### PR DESCRIPTION
**Pull request by yacoob**
As far as I can tell this confuses `basedpyright`, when it tries to check modules present in beancount but not having a type stub in beancount-stubs. With `beancount-stubs/__init__.pyi` in place, it fails to find `beancount.ingest` and anything below. With that file gone, it resolves the import correctly and analyzes `beancount.ingest` directly.

So in other words: this change doesn't bring more type signatures in, but at least makes sure the typechecker doesn't get lost trying to find the original module :D

If all goes well, I'll try to send you another pull request for `beancount.ingest.{cache,importer,regression_pytest}` :)

### CODE REVIEW

**Comment by Goorzhel** [comment]
This diff restores  `poetry build`:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index a84adf1..87c87f1 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -7,4 +7 @@ license = "MIT"
-packages = [
-    { include = "beancount-stubs" },
-    { include = "beancount-stubs/**/*.pyi" },
-]
+packages = [{include = "beancount-stubs"}]
```

Before and after:
```sh
$ poetry build
Building beancount-stubs (0.1.3)
  - Building sdist

account.pyi is not a package.
```
```
❯ poetry build
Building beancount-stubs (0.1.3)
  - Building sdist
  - Built beancount_stubs-0.1.3.tar.gz
  - Building wheel
  - Built beancount_stubs-0.1.3-py3-none-any.whl
```

**Comment by yacoob** [comment]
Oh, a nice side effect :) Having had some problems with `poetry` in the past, I've only verified it builds via `setup.py`. The workflow seem to use that path too.

Thanks for pointing that out :)

**Comment by yacoob** [comment]
Hey @jmgilman - would you be interested in transfering ownership of this repository and the respective pypi package? I think I'd have some bandwidth right now to maintain it - review all outstanding PRs and maybe add more types.

I'm fine either way, as long as I get the fixes for the types I've used in :)

**Comment by jmgilman** [comment]
Hey @yacoob, I did see your PRs but had it on my list to check things out this weekend. Great work, by the way. I'd be happy to add as you as a full maintainer so my limited time doesn't block you.

**Pull request merged**
